    printf("1. Agregar libro\n");
    printf("2. Eliminar libro\n");
    printf("3. Agregar campus\n");
    printf("4. Eliminar campus\n");
    printf("5. Agregar seccion\n");
    printf("6. Eliminar seccion\n");
    printf("7. Agregar estante\n");
    printf("8. Eliminar estante\n");
    printf("9. Cambiar campus\n");
    printf("10. Cambiar seccion\n");
    printf("11. Cambiar estante\n");
    printf("12. Buscar libro\n");
    printf("13. Editar libro\n");
    printf("14. Salir\n");